project-name: Description

# default queue for CPU tasks
queue-default: "desc_preparation"

# default queue for GPU tasks
queue-gpu: "desc_preparation"

# default queue for service tasks
queue-service: "services"

# cache limit for number of files for local downloads. The oldest will be removed if limit is exceeded
storage-cache-limit: 3

# Runs pipeline remotely. If false, all pipeline tasks runs on local machine
# This should be set to true on production and staging
pipeline-remote-execution: false
